### ISSUE TITLE
[Checklist] Upgrade SVN to 1.4.3

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/leads#67]
Check list for new version deploy
- [x]  Update main file version numbers
- [x]  Update readme.txt & change log from viewing closed github issues. 
- [x]  Update change log on docs.inboundnow.com: http://docs.inboundnow.com/changelogs/leads/
- [x] Test new version installation against older released versions of LP & CTA
- [x]  Manual Unit Tests
  - [x] Make sure lead stores during a form submission
  - [x] Make sure page view counts are incrementing for lead
  - [x] Make sure conversion counts are incrementing for lead
- [x]  Install latest lp & cta & repeat manual unit tests above. 
- [x]  Deploy plugin update. 
- [x]  Announce plugin update to Twitter.
- [x]  Announce plugin update to Facebook. 
- [x]  Announce plugin update to Email?
